services:
  - type: web
    name: lispick
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: "composer install"
    startCommand: "php artisan serve --host 0.0.0.0 --port 8000"
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production